// What `nmts` prints when asked what it can do.
//
// ⛔ COMMANDS THAT ARE NOT BUILT ARE MARKED, NOT HIDDEN. An agent that discovers a command by
//    running it and getting "unknown command" learns the wrong thing — it will try synonyms. Being
//    told the command exists and is unfinished is a fact it can act on: stop, and do not retry.

import { AGENTS_DOC, BINARY_NAME, HOME_URL, PRODUCT_NAME, SOURCE_URL } from "./product.ts";
import {
  API_KEY_ENV_VAR,
  API_KEY_FILE_ENV_VAR,
  CODE_ENV_VAR,
  CODE_FILE_ENV_VAR,
  PASSPHRASE_ENV_VAR,
} from "./credentials.ts";
import { NETWORK_ENV_VAR } from "./network.ts";
import { SERVER_ENV_VAR } from "./server.ts";
import { AGGREGATOR_ENV_VAR } from "./walrus.ts";
import {
  CHECK_DOES_NOT_PROVE,
  CHECK_PROVES,
  RECOVERY_TOOL_URL,
  wrapText,
} from "./recovery-release.ts";

export function helpText(version: string): string {
  return [
    `${PRODUCT_NAME} ${version} — command-line access to end-to-end encrypted NMTS storage.`,
    ``,
    `USAGE`,
    `  ${BINARY_NAME} <command> [options]`,
    ``,
    `COMMANDS`,
    `  login                 Keep an account code on this machine, sealed — and take an API key`,
    `  logout                Remove the stored account code`,
    `  whoami                Show which account the stored code belongs to (offline)`,
    `  create                Make a NEW account. Prints its code once — nothing can print it again`,
    `  ls                    List files in the account`,
    `  usage                 What the account holds: counts, bytes, largest files, trash`,
    `  balance               Credits left, what they buy, and the ceilings on spending`,
    `  trial                 What is left of this week's free credits. \`trial apply\` asks for some`,
    `  expiring              List files whose bought storage runs out soon`,
    `  extend <path>         Buy more storage time for one file — **spends WAL from the wallet**`,
    `  public-code           The code other accounts send files to. \`--publish\` makes it reachable`,
    `  wallet                Show the account's wallet address, and its SUI and WAL balances`,
    `  wallet address        Just the address, derived on this machine — no network call`,
    `  put <file>            Encrypt one file and upload it, paid with credits`,
    `  get <path>            Download one file and decrypt it`,
    `  pull [folder]         Download a whole folder, or the whole account, keeping its shape`,
    `  push <directory>      Upload a whole directory, keeping its shape — **spends credits**`,
    `  rm <paths>            Move things to the trash — restorable for 30 days`,
    `  restore <paths>       Bring things back out of the trash`,
    `  sweep                 Drop trash entries whose 30 days have run out. Asks first`,
    `  rebuild               Build a file list from the server's rows, for an account with none`,
    `  listfile              Write this machine's copy of the sealed file list out as a file`,
    `  mkdir <path>          Make a folder, and any folder above it that is missing`,
    `  mv <paths> <folder>   Move things into a folder. \`/\` is the top of the drive`,
    `  rename <path> <name>  Give one thing a new name`,
    `  star <files>          Star files — they are gathered in favourites as well`,
    `  unstar <files>        Take the star off`,
    `  pin <files>           Hold files at the top of the folder they are in`,
    `  unpin <files>         Let them fall back into the ordinary order`,
    `  label <name> <files>  Put one label on files. A label exists while a file wears it`,
    `  unlabel <name> <files>`,
    `                        Take one label off files`,
    `  share <path> <addr>   Give one file to another account. Withdrawing does not recall it`,
    `  shares                What was shared with this account`,
    `  receive <id>          Download one file somebody shared with this account`,
    `  unshare <id>          Withdraw a share you sent, or remove one you were sent`,
    `  env                   What this machine is, and what it means for the account code`,
    `  consent               See what this machine has agreed to, and change it`,
    `  recovery              Download the standalone program that reads files back without NMTS`,
    `  recovery-list         Write the file that finds your bytes without NMTS. Holds no code`,
    `  kit                   Recovery kit: that list AND your account code, together in one file`,
    `  verify                Ask a person to pass the check that opens this account's limits`,
    `  mcp                   Serve ls, get and put as tools, for an agent that speaks MCP`,
    ``,
    `OPTIONS`,
    `  --server <url>        NMTS server (default ${SERVER_ENV_VAR} or the live one)`,
    `  --network <name>      mainnet or testnet. Required for any server but the live one`,
    `  --json                Machine-readable output (ls, usage, get, put, env, verify,`,
    `                        expiring, sweep, rebuild, pull, wallet, shares, share, receive,`,
    `                        recovery, balance, trial, extend, recovery-list, kit, create —`,
    `                        create needs --out as well, so the code never enters the output)`,
    `  --all                 Include what is in the trash (ls)`,
    `  --find <text>         List only the files whose name contains this text (ls). Folders`,
    `                        appear only where they hold a match`,
    `  --sort <key>          name, size or date. Default: whole paths, ascending (ls)`,
    `  --desc                Reverse whichever order is in effect (ls)`,
    `  --hidden              Include entries whose name begins with a dot (push)`,
    `  --out <path>          Where to write files (get, pull, mcp, listfile, recovery,`,
    `                        recovery-list, kit, create). Default: here`,
    `  --out -               Send a fetched file to stdout instead of writing it (get, listfile)`,
    `  --force               Replace a file that is already there (get, pull, listfile,`,
    `                        recovery, recovery-list, kit), or rebuild an account this machine`,
    `                        has seen a list for (rebuild). \`create\` never replaces a file`,
    `  --name <name>         The name the uploaded file gets in the drive (put)`,
    `  --to <folder>         Destination folder, as \`${BINARY_NAME} ls\` prints it (put, push)`,
    `  --dry-run             Say what it would cost, and stop (put, push, extend). With`,
    `                        \`extend\` nothing is signed and the wallet key is never touched`,
    `  --part-size <n>       Bytes per part for a large upload (put, push). Default 64MiB.`,
    `                        a plain number, or one with KiB, MiB or GiB. Bigger parts mean`,
    `                        fewer purchases; smaller parts use less memory`,
    `  --yes                 Go ahead with something that cannot be taken back (sweep, rebuild),`,
    `                        or extend a file that is nowhere near its deadline (extend)`,
    `  --epochs <n>          How many of the storage network's epochs to add (extend)`,
    `  --accept-terms <v>    The version of the Terms of Service a PERSON read and accepts for`,
    `                        the new account (create). A version, never "the current one"`,
    `  --accept-privacy <v>  The version of the Privacy Policy accepted in the same act (create)`,
    `  --publish             Publish this account's public code (public-code). Permanent —`,
    `                        it cannot be withdrawn or changed afterwards`,
    `  --status              Say whether the check is live, and stop (verify)`,
    `  --plain               Store the code unsealed instead (login). Asks for an agreement`,
    `  --env                 Store nothing; print the variable to set (login). Same agreement`,
  `  --version             Print the version and exit`,
    `  --help                Print this and exit`,
    ``,
    `ENVIRONMENT`,
    `  ${CODE_FILE_ENV_VAR.padEnd(24)}Names a FILE holding the account code. The recommended way, and`,
    `                          the only one that asks nothing: the file is read, never copied.`,
    `  ${CODE_ENV_VAR.padEnd(24)}The account code itself. Takes precedence over anything stored,`,
    `                          and asks once — an environment variable is readable through`,
    `                          \`docker inspect\`, /proc/<pid>/environ and most CI logs.`,
    `  ${PASSPHRASE_ENV_VAR.padEnd(24)}Opens a sealed stored code without a terminal.`,
    `  ${API_KEY_FILE_ENV_VAR.padEnd(24)}Names a FILE holding the API key. \`${BINARY_NAME} login\` reads this`,
    `                          first, and a container cannot leak it the way it leaks a value.`,
    `  ${API_KEY_ENV_VAR.padEnd(24)}Key made on the account screen. It waives the human check a`,
    `                          browser sign-in does, and nothing else — it opens no file.`,
    `                          \`${BINARY_NAME} login\` checks one it finds here with the server and`,
    `                          then stores it, so it outlives the terminal it was set in.`,
    `  ${SERVER_ENV_VAR.padEnd(24)}Server to talk to. For development stacks.`,
    `  ${AGGREGATOR_ENV_VAR.padEnd(24)}Storage-network read hosts, comma-separated. Replaces`,
    `                          the built-in list rather than adding to it.`,
    `  ${NETWORK_ENV_VAR.padEnd(24)}mainnet or testnet. Never guessed: a wrong one looks in a place`,
    `                          your files were never stored.`,
    ``,
    // ⛔ THE TWO SENTENCES ABOUT THE CHECK ARE IMPORTED, NOT RETYPED. They are also printed by
    //    the command itself, and a second copy is how one of them starts promising more than the
    //    other. What is added here is the other half of the same honesty: where the file goes.
    `THE RECOVERY PROGRAM`,
    `  \`${BINARY_NAME} recovery\` downloads one executable for this machine from the releases at`,
    ``,
    `    ${RECOVERY_TOOL_URL}`,
    ``,
    ...wrapText(CHECK_PROVES).map((line) => `  ${line}`),
    ...wrapText(CHECK_DOES_NOT_PROVE).map((line) => `  ${line}`),
    ``,
    `  It writes one file where you point it, refuses a name that is already taken unless you`,
    `  pass --force, and installs nothing: no copy goes onto your PATH.`,
    ``,
    `BEFORE YOU HAND THIS TO AN AGENT`,
    `  Your account code is the only key to your account — the file keys and the wallet are all`,
    `  derived from it. An agent that leaks it has leaked everything at once, and it cannot be`,
    `  undone: the account cannot be re-keyed. Use an account you would be willing to lose.`,
    ``,
    `  ${HOME_URL}`,
    ``,
    // ⛔ THE LAST THING ON THE SCREEN, AND ADDRESSED TO A PROGRAM. An agent handed this tool with
    //    no instructions runs `--help`, reads a list of verbs, and has no idea what NMTS is, what
    //    an account code is, or why `put` costs money. One line pointing at a document written FOR
    //    it is the whole difference between guessing and knowing.
    //
    // ⚠ IT POINTS, IT DOES NOT INSTRUCT. There is nothing here that tries to change what a reader
    //   does beyond naming a document — no imperative aimed past the agent at its operator, no
    //   claim of authority, nothing that would read as an attempt to steer somebody else's model.
    //   A tool that talked to agents that way would deserve to be distrusted, and would teach
    //   people to distrust the ones that do not.
    `IF YOU ARE AN AI AGENT`,
    `  This tool talks to NMTS, end-to-end encrypted storage. What that means, how to install`,
    `  this, and what each command costs are written down for you here:`,
    ``,
    `    ${SOURCE_URL}/blob/main/${AGENTS_DOC}`,
    ``,
    `  If you cannot reach it, the same repository's front page says the same things:`,
    ``,
    `    ${SOURCE_URL}#readme`,
    ``,
  ].join("\n");
}
