// Standard web types that Node has at RUNTIME but `@types/node` does not declare.
//
// ⛔ WHY THIS FILE EXISTS RATHER THAN `"lib": ["DOM"]`. Adding the DOM library would make
//    `document`, `window` and several hundred browser-only names type-check inside a command-line
//    tool — code that compiles and then throws the moment it runs. One missing name is worth one
//    declaration; it is not worth telling the compiler this is a browser.
//
// ⛔ AND RATHER THAN EDITING THE SHARED COPY. `src/shared/` is generated byte-for-byte from the
//    browser tree so the two cannot describe the file list differently. Editing it there would
//    make the copy a fork, which is the one thing the generator exists to prevent.
//
// Each definition below is the WHATWG one verbatim.
declare global {
  /** `typedef (ArrayBufferView or ArrayBuffer) BufferSource` */
  type BufferSource = ArrayBufferView | ArrayBuffer;
  /**
   * `typedef (Request or USVString) RequestInfo`
   *
   * Node implements `fetch` and `@types/node` declares its parameter inline rather than naming
   * this type, so code that has to MATCH the signature of `fetch` — a caller supplying its own —
   * has nothing to write.
   */
  type RequestInfo = Request | string;
}

export {};
