// Standard web types that Node has at RUNTIME but `@types/node` does not declare.
//
// ⛔ WHY THIS FILE EXISTS RATHER THAN `"lib": ["DOM"]`. Adding the DOM library would make
//    `document`, `window` and several hundred browser-only names type-check inside a command-line
//    tool — code that compiles and then throws the moment it runs. One missing name is worth one
//    declaration; it is not worth telling the compiler this is a browser.
//
// ⛔ AND RATHER THAN EDITING THE SHARED COPY. `src/shared/` is generated byte-for-byte from the
//    browser tree so the two cannot describe the file list differently. Editing it there would
//    make the copy a fork, which is the one thing the generator exists to prevent.
//
// The definition is the WHATWG one verbatim: `typedef (ArrayBufferView or ArrayBuffer) BufferSource`.
declare global {
  type BufferSource = ArrayBufferView | ArrayBuffer;
}

export {};
